image: php:7-apache
services:
  - mysql:latest

variables:
  MYSQL_DATABASE: homestead
  MYSQL_ROOT_PASSWORD: secret
  MYSQL_PASSWORD: secret

before_script:
  # Update packages 
  - apt-get update -yqq
  - apt-get install git nodejs libcurl4-gnutls-dev libicu-dev libmcrypt-dev libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev libpq-dev libsqlite3-dev libaspell-dev libsnmp-dev libpcre3-dev libtidy-dev -yqq
  - docker-php-ext-install mbstring mcrypt pdo_mysql curl json intl gd xml zip bz2 opcache
  - curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
  - php /usr/local/bin/composer install 
  - cp .env.example .env
  
  - php artisan key:generate
  - php artisan config:cache

  - php artisan migrate

  - php artisan db:seed

#after_script:
#  - rm secrets

stages:
  - build
  - test
  - deploy

job1:
  stage: build
  script:
    - echo '1'

job2:
  stage: test
  script:
    - echo '2'

job3:
  stage: deploy
  script:
    - echo '3'
