version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/var/www/html/
    ports:
      - '80:80'
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ifcitec
    ports:
      - '5432:5432'
  #phppgadmin:
  #  image: phpmyadmin/phpmyadmin

  #  environment:
  #  - PMA_HOST=mysql
  #  - PMA_PASSWORD=secret
  #  - PMA_USER=root
  #  ports:
  #    - '8080:80'
