FROM php:7.1.7-apache
RUN apt-get update -yqq && \
    apt-get install nano libzip-dev zlib1g-dev libpq-dev libpng-dev -yqq --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install zip pdo_pgsql pgsql gd
RUN a2dissite * && a2enmod rewrite

#COPY ./ /var/www/html

COPY laravel-virtualhost.conf /etc/apache2/sites-available/

COPY ci/customphp.ini /usr/local/etc/php/conf.d/

RUN a2ensite laravel-virtualhost.conf
