FROM php:7.1.7-apache
RUN apt-get update -yqq && \
    apt-get install nano zlib1g-dev libpq-dev -yqq --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install zip pdo_pgsql pgsql
RUN a2dissite * && a2enmod rewrite
COPY laravel-virtualhost.conf /etc/apache2/sites-available/
RUN echo 'max_execution_time = 600' > /usr/local/etc/php/conf.d/customphp.ini
RUN a2ensite laravel-virtualhost.conf
