version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/var/www/html/
    ports:
      - '80:80'
    links:
      - mysql
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=homestead
    ports:
      - '3306:3306'
  phpmyadmin:
    image: phpmyadmin/phpmyadmin

    environment:
    - PMA_HOST=mysql
    - PMA_PASSWORD=secret
    - PMA_USER=root
    ports:
      - '8080:80'
