version: '2'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/var/www/html/
    ports:
      - '80:80'
    links:
      - postgres
  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ifcitec
    ports:
      - '5432:5432'
  phppgadmin:
    image: tozd/phppgadmin
    environment:
      - PHPPGADMIN_HOST=postgres
      - PHPPGADMIN_PORT=5432
    #image: jacksoncage/phppgadmin
    #environment:
    #- POSTGRES_HOST=postgres
    #- POSTGRES_PORT=5432
    #- APACHE_SERVERNAME=pwd10-0-9-3-80.host2.labs.play-with-docker.com
    ports:
      - '8080:80'
