version: "3"

services:
  web:
    container_name: ifcitecweb
    image: ifrscanoas/ifcitec:latest
    expose:
      - "80"
    networks:
      - net-web
      - net-db
#    volumes:
#      - ./.env:/var/www/html/.env
    env_file:
      - .env

  postgres:
    image: postgres:9.6.3
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - vol-ifcitec-inscricao/:/var/lib/postgresql/data:rw
    networks:
      - net-db

#  phppgadmin:
#    image: tozd/phppgadmin
#    environment:
#      - PHPPGADMIN_HOST=postgres
#      - PHPPGADMIN_PORT=5432
    #expose:
#    ports:
#      - '980:80'
    #  - '80'
#    networks:
#      - net-web
#      - net-db
volumes:
  vol-ifcitec-inscricao:
    external: true

networks:
    net-web:
     external:
      name: net-web
    net-db:
     external:
      name: net-db
