version: '2'

services:
  web:
    container_name: ifcitecweb
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/var/www/html/
    ports:
      - '8088:80'
    links:
      - postgres

  postgres:
    image: postgres:9.3
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ifcitec
    ports:
      - '5432'

  phppgadmin:
    image: bitnami/phppgadmin
    env_file: pgadmin.env
    ports:
      - '8080:8080'
