version: "3.9"

services:
  web:
    container_name: ifcitecweb
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - ./:/var/www/html/
    ports:
      - '8088:80'
    links:
      - postgres

  postgres:
    build:
      context: .
      dockerfile: Dockerfile-postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=ifcitec
    ports:
      - "15432:5432"
    networks:
      - ifcitec-compose-network

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "ifcitec@canoas.ifrs.edu.br"
      PGADMIN_DEFAULT_PASSWORD: "123"
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - ifcitec-compose-network

networks:
  ifcitec-compose-network:
    driver: bridge
