FROM php:7.0-apache
RUN apt-get update -yqq && \
    apt-get install openssl libcurl4-gnutls-dev libicu-dev libmcrypt-dev \
    libvpx-dev libjpeg-dev libpng-dev libxpm-dev zlib1g-dev libfreetype6-dev \
    libxml2-dev libexpat1-dev libbz2-dev libgmp3-dev libldap2-dev unixodbc-dev \
    libpq-dev libsqlite3-dev libaspell-dev libpcre3-dev libtidy-dev libpq-dev -yqq && \
    rm -rf /var/lib/apt/lists/*
RUN docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql
RUN docker-php-ext-install mbstring mcrypt pdo_mysql curl json gd xml zip bz2 pdo pdo_pgsql pgsql
RUN a2dissite * && a2enmod rewrite
COPY laravel-virtualhost.conf /etc/apache2/sites-available/
RUN a2ensite laravel-virtualhost.conf